# Generated by Django 5.2.6 on 2025-09-13 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_prevista_devolucao', models.DateTimeField()),
                ('data_efetiva_devolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Emprestado', 'Emprestado'), ('Em Uso', 'Em Uso'), ('Fornecido', 'Fornecido'), ('Devolvido', 'Devolvido'), ('Danificado', 'Danificado'), ('Perdido', 'Perdido')], default='Emprestado', max_length=20)),
                ('observacao_devolucao', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_control.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_control.equipamento')),
            ],
        ),
    ]
