# Generated by Django 5.2.6 on 2025-09-13 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_control', '0002_equipamento_data_aquisicao_equipamento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_control.colaborador', verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_control.equipamento', verbose_name='Equipamento'),
        ),
        migrations.CreateModel(
            name='ControleEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Entrega')),
                ('data_prevista_devolucao', models.DateTimeField(verbose_name='Data Prevista de Devolução')),
                ('data_efetiva_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data Efetiva de Devolução')),
                ('status', models.CharField(choices=[('emprestado', 'Emprestado'), ('em_uso', 'Em Uso'), ('fornecido', 'Fornecido'), ('devolvido', 'Devolvido'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='emprestado', max_length=20, verbose_name='Status')),
                ('observacao_devolucao', models.TextField(blank=True, null=True, verbose_name='Observação na Devolução')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_control.colaborador', verbose_name='Colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_control.equipamento', verbose_name='Equipamento')),
            ],
        ),
    ]
